name = "alr_appimage"
description = "Tool to automatically create an AppImage excutable from an Alire"
version = "0.1.0-dev"

authors = ["Manuel Gomez"]
maintainers = ["Manuel Gomez <mgrojo@gmail.com>"]
maintainers-logins = ["mgrojo"]

executables = ["alr_appimage"]
[[depends-on]]
ada_toml = "~0.3.0"

[[depends-on]]
spoon = "^1.0.1"

[[depends-on]]
parse_args = "~0.9.0"
