name = "alr_appimage"
description = "Tool to create an AppImage executable from an Alire crate"
version = "0.1.0-dev"
licenses = "GPL-3.0-only"

tags = ["utility", "appimage", "alire", "linux", "packaging"]

authors = ["Manuel Gomez"]
maintainers = ["Manuel Gomez <mgrojo@gmail.com>"]
maintainers-logins = ["mgrojo"]

executables = ["alr_appimage"]
[[depends-on]]
ada_toml = "~0.3.0"

[[depends-on]]
spoon = "^1.0.1"

[[depends-on]]
parse_args = "~0.9.0"
